In [1]:
# (1) 필요한 모듈 import 
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

# (2) 데이터 준비
wines = load_wine()

# (3) 데이터 이해하기

# Feature Data 지정하기  (머신러닝 모델에게 입력되는 데이터를 feature 라고 부르기도 한다.)
wines_data = wines.data

# Label Data 지정하기
wines_label = wines.target

# Target Names 출력해 보기
print("Target_names :", wines.target_names, "\n")

# 데이터 Describe 해 보기
print("wines 데이터의 자료형 :", type(dir(wines)),"\n")
print("wines 데이터에 담긴 정보들 :", wines.keys(),"\n")
print("wines 데이터의 feature의 shape(총 데이터수, 각 데이터가 갖고 있는 정보의 수) :", wines_data.shape,"\n")
# print("wines 데이터의 feature의 맨 첫번째 데이터에 입력된 정보 :", wines_data[0])
print("wines 데이터의 총 label 개수 :", wines_label.shape,"\n")

# print(digits.DESCR)

wines_df = pd.DataFrame(data=wines_data, columns=wines.feature_names) 
wines_df["label"] = wines.target
print("wines 데이터의 각 feature와 target의 값 :")
wines_df


Target_names : ['class_0' 'class_1' 'class_2'] 

wines 데이터의 자료형 : <class 'list'> 

wines 데이터에 담긴 정보들 : dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names']) 

wines 데이터의 feature의 shape(총 데이터수, 각 데이터가 갖고 있는 정보의 수) : (178, 13) 

wines 데이터의 총 label 개수 : (178,) 

wines 데이터의 각 feature와 target의 값 :


alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  label  
0                            3.92   1065.0      0  
1                            3.40   1050.0      0  
2                            3.17   1185.0      0  
3                            3.45   1480.0      0  
4                            2.93    735.0      0  
..                            ...      ...    ...  
173                          1.74    740.0      2  
174                          1.56    750.0      2  
175                          1.56    835.0      2  
176                          1.62    840.0      2  
177                          1.60    560.0      2  

[178 rows x 14 columns]

In [3]:
# (4) train, test 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(wines_data, 
                                                    wines_label, 
                                                    test_size=0.2, 
                                                    random_state= 25)

In [4]:
# (4) 모델 학습 및 예측, 

# 첫번째 알고리즘 : Decision Tree 92%
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(random_state=32)
decision_tree.fit(X_train, y_train)
y_pred = decision_tree.predict(X_test)

print("confusion_matrix : ","\n", confusion_matrix(y_test, y_pred), "\n")
print("classification_report : ","\n", classification_report(y_test, y_pred), "\n")

confusion_matrix :  
 [[10  1  0]
 [ 1 16  1]
 [ 0  0  7]] 

classification_report :  
               precision    recall  f1-score   support

           0       0.91      0.91      0.91        11
           1       0.94      0.89      0.91        18
           2       0.88      1.00      0.93         7

    accuracy                           0.92        36
   macro avg       0.91      0.93      0.92        36
weighted avg       0.92      0.92      0.92        36
 



In [5]:
# 두번째 알고리즘 : Random Forest 100%
from sklearn.ensemble import RandomForestClassifier


random_forest = RandomForestClassifier(random_state=32)
random_forest.fit(X_train, y_train)
y_pred = random_forest.predict(X_test)

print("confusion_matrix : ","\n", confusion_matrix(y_test, y_pred), "\n")
print("classification_report : ","\n", classification_report(y_test, y_pred), "\n")

confusion_matrix :  
 [[11  0  0]
 [ 0 18  0]
 [ 0  0  7]] 

classification_report :  
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00         7

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36
 



In [6]:
# 세번째 알고리즘 : Support Vector Machine 72%
from sklearn import svm

svm_model = svm.SVC()
svm_model.fit(X_train, y_train)
y_pred = svm_model.predict(X_test)

print("confusion_matrix : ","\n", confusion_matrix(y_test, y_pred), "\n")
print("classification_report : ","\n", classification_report(y_test, y_pred), "\n")

confusion_matrix :  
 [[ 8  0  3]
 [ 1 14  3]
 [ 0  3  4]] 

classification_report :  
               precision    recall  f1-score   support

           0       0.89      0.73      0.80        11
           1       0.82      0.78      0.80        18
           2       0.40      0.57      0.47         7

    accuracy                           0.72        36
   macro avg       0.70      0.69      0.69        36
weighted avg       0.76      0.72      0.74        36
 



In [7]:
# 네번째 알고리즘 : Stochastic Gradient Descent Classifier (SGDClassifier)  67%  

from sklearn.linear_model import SGDClassifier


sgd_model = SGDClassifier()
sgd_model.fit(X_train, y_train)
y_pred = sgd_model.predict(X_test)

print("confusion_matrix : ","\n", confusion_matrix(y_test, y_pred), "\n")
print("classification_report : ","\n", classification_report(y_test, y_pred), "\n")

confusion_matrix :  
 [[ 8  0  3]
 [ 1 11  6]
 [ 2  0  5]] 

classification_report :  
               precision    recall  f1-score   support

           0       0.73      0.73      0.73        11
           1       1.00      0.61      0.76        18
           2       0.36      0.71      0.48         7

    accuracy                           0.67        36
   macro avg       0.69      0.68      0.65        36
weighted avg       0.79      0.67      0.69        36
 



In [8]:
# 다섯번째 알고리즘 : Logistic Regression  69%

from sklearn.linear_model import LogisticRegression
import numpy as np


print('최소값:',np.min(X_train), ' 최대값:',np.max(X_train))
print('최소값:',np.min(X_test), ' 최대값:',np.max(X_test))

최소값: 0.13  최대값: 1680.0
최소값: 0.14  최대값: 1515.0


In [13]:
# X_train 과 X_test Normalization
X_train_norm = X_train/255.0 
X_test_norm = X_test/255.0 

print('최소값:',np.min(X_train_norm), ' 최대값:',np.max(X_train_norm))
print('최소값:',np.min(X_test_norm), ' 최대값:',np.max(X_test_norm))

logistic_model = LogisticRegression()

logistic_model.fit(X_train_norm, y_train)
y_pred = logistic_model.predict(X_test_norm)

print("confusion_matrix : ","\n", confusion_matrix(y_test, y_pred), "\n")
print("classification_report : ","\n", classification_report(y_test, y_pred), "\n")

최소값: 0.0005098039215686275  최대값: 6.588235294117647
최소값: 0.0005490196078431374  최대값: 5.9411764705882355
confusion_matrix :  
 [[ 8  0  3]
 [ 1 14  3]
 [ 1  3  3]] 

classification_report :  
               precision    recall  f1-score   support

           0       0.80      0.73      0.76        11
           1       0.82      0.78      0.80        18
           2       0.33      0.43      0.38         7

    accuracy                           0.69        36
   macro avg       0.65      0.64      0.65        36
weighted avg       0.72      0.69      0.71        36
 



In [ ]:
와인 분류 문제에서 가장 좋은 성능을 낸 모델 : Random forest

In [15]:
이 문제는 총 178개의 와인을 3개의 카테고리로 분류하는 최고의 알고리즘을 찾는 문제다.
이를 위해 각 와인 당 13개의 feature가 입력돼있다.
랜덤 포레스트는 모든 지표에서 100%의 성적을 냈다.
(3개의 와인 카테고리에서 각각 precision, recall, f1-score가 모두 100%)
따라서 이 문제에 있어서는 랜덤 포레스트가 최선의 모델이라고 할 수 있다

그렇다면 왜 랜덤 포레스트가 최고의 결과를 낼 수 있었던 걸까?
타겟의 종류가 적고, 그에 비해 상대적으로 feature가 많은 문제에선 랜덤 포레스트가 좋은 성능을 낸다고 추론해볼 수 있다.

SyntaxError: invalid syntax (<ipython-input-15-5366686037eb>, line 1)

In [ ]:
winedml SVM 과 SGDClassifier 모델의 성적이 digits와 breast_cancer보다 유난히 떨어진다. 왜?