In [1]:
# (1) 필요한 모듈 import 
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

# (2) 데이터 준비
breast_cancer = load_breast_cancer()

# (3) 데이터 이해하기

# Feature Data 지정하기  (머신러닝 모델에게 입력되는 데이터를 feature 라고 부르기도 한다.)
breast_cancer_data = breast_cancer.data

# Label Data 지정하기
breast_cancer_label = breast_cancer.target

# Target Names 출력해 보기
print("Target_names :", breast_cancer.target_names, "\n")

# 데이터 Describe 해 보기
print("breast_cancer 데이터의 자료형 :", type(dir(breast_cancer)),"\n")
print("breast_cancer 데이터에 담긴 정보들 :", breast_cancer.keys(),"\n")
print("breast_cancer 데이터의 feature의 shape(총 데이터수, 각 데이터가 갖고 있는 정보의 수) :", breast_cancer_data.shape,"\n")
# print("breast_cancer 데이터의 feature의 맨 첫번째 데이터에 입력된 정보 :", breast_cancer_data[0]) 
print("breast_cancer 데이터의 총 label 개수 :", breast_cancer_label.shape,"\n")

# print(breast_cancer.DESCR)

breast_cancer_df = pd.DataFrame(data=breast_cancer_data, columns=breast_cancer.feature_names) 
breast_cancer_df["label"] = breast_cancer.target
print("breast_cancer 데이터의 각 feature와 target의 값 :")
breast_cancer_df

Target_names : ['malignant' 'benign'] 

breast_cancer 데이터의 자료형 : <class 'list'> 

breast_cancer 데이터에 담긴 정보들 : dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename']) 

breast_cancer 데이터의 feature의 shape(총 데이터수, 각 데이터가 갖고 있는 정보의 수) : (569, 30) 

breast_cancer 데이터의 총 label 개수 : (569,) 

breast_cancer 데이터의 각 feature와 target의 값 :


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  label  
0                  0.2654          0.4601                  0.11890      0  
1                  0.1860          0.2750                  0.08902      0  
2                  0.2430          0.3613                  0.08758      0  
3                  0.2575          0.6638                  0.17300      0  
4                  0.1625          0.2364                  0.07678   

In [2]:
# (4) train, test 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(breast_cancer_data, 
                                                    breast_cancer_label, 
                                                    test_size=0.2, 
                                                    random_state= 25)

In [3]:
# (4) 모델 학습 및 예측, 

# 첫번째 알고리즘 : Decision Tree 92%
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(random_state=32)
decision_tree.fit(X_train, y_train)
y_pred = decision_tree.predict(X_test)

print("confusion_matrix : ","\n", confusion_matrix(y_test, y_pred), "\n")
print("classification_report : ","\n", classification_report(y_test, y_pred), "\n")

confusion_matrix :  
 [[34  5]
 [ 4 71]] 

classification_report :  
               precision    recall  f1-score   support

           0       0.89      0.87      0.88        39
           1       0.93      0.95      0.94        75

    accuracy                           0.92       114
   macro avg       0.91      0.91      0.91       114
weighted avg       0.92      0.92      0.92       114
 



In [4]:
# 두번째 알고리즘 : Random Forest 94%
from sklearn.ensemble import RandomForestClassifier


random_forest = RandomForestClassifier(random_state=32)
random_forest.fit(X_train, y_train)
y_pred = random_forest.predict(X_test)

print("confusion_matrix : ","\n", confusion_matrix(y_test, y_pred), "\n")
print("classification_report : ","\n", classification_report(y_test, y_pred), "\n")

confusion_matrix :  
 [[35  4]
 [ 3 72]] 

classification_report :  
               precision    recall  f1-score   support

           0       0.92      0.90      0.91        39
           1       0.95      0.96      0.95        75

    accuracy                           0.94       114
   macro avg       0.93      0.93      0.93       114
weighted avg       0.94      0.94      0.94       114
 



In [5]:
# 세번째 알고리즘 : Support Vector Machine 91%
from sklearn import svm

svm_model = svm.SVC()
svm_model.fit(X_train, y_train)
y_pred = svm_model.predict(X_test)

print("confusion_matrix : ","\n", confusion_matrix(y_test, y_pred), "\n")
print("classification_report : ","\n", classification_report(y_test, y_pred), "\n")

confusion_matrix :  
 [[30  9]
 [ 1 74]] 

classification_report :  
               precision    recall  f1-score   support

           0       0.97      0.77      0.86        39
           1       0.89      0.99      0.94        75

    accuracy                           0.91       114
   macro avg       0.93      0.88      0.90       114
weighted avg       0.92      0.91      0.91       114
 



In [6]:
# 네번째 알고리즘 : Stochastic Gradient Descent Classifier (SGDClassifier)  92%

from sklearn.linear_model import SGDClassifier


sgd_model = SGDClassifier()
sgd_model.fit(X_train, y_train)
y_pred = sgd_model.predict(X_test)

print("confusion_matrix : ","\n", confusion_matrix(y_test, y_pred), "\n")
print("classification_report : ","\n", classification_report(y_test, y_pred), "\n")

confusion_matrix :  
 [[33  6]
 [ 3 72]] 

classification_report :  
               precision    recall  f1-score   support

           0       0.92      0.85      0.88        39
           1       0.92      0.96      0.94        75

    accuracy                           0.92       114
   macro avg       0.92      0.90      0.91       114
weighted avg       0.92      0.92      0.92       114
 



In [7]:
# 다섯번째 알고리즘 : Logistic Regression  90%

from sklearn.linear_model import LogisticRegression
import numpy as np


print('최소값:',np.min(X_train), ' 최대값:',np.max(X_train))
print('최소값:',np.min(X_test), ' 최대값:',np.max(X_test))

최소값: 0.0  최대값: 4254.0
최소값: 0.0  최대값: 2615.0


In [8]:
# X_train 과 X_test Normalization
X_train_norm = X_train/255.0 
X_test_norm = X_test/255.0 

print('최소값:',np.min(X_train_norm), ' 최대값:',np.max(X_train_norm))
print('최소값:',np.min(X_test_norm), ' 최대값:',np.max(X_test_norm))

logistic_model = LogisticRegression()

logistic_model.fit(X_train_norm, y_train)
y_pred = logistic_model.predict(X_test_norm)

print("confusion_matrix : ","\n", confusion_matrix(y_test, y_pred), "\n")
print("classification_report : ","\n", classification_report(y_test, y_pred), "\n")

최소값: 0.0  최대값: 16.68235294117647
최소값: 0.0  최대값: 10.254901960784315
confusion_matrix :  
 [[31  8]
 [ 3 72]] 

classification_report :  
               precision    recall  f1-score   support

           0       0.91      0.79      0.85        39
           1       0.90      0.96      0.93        75

    accuracy                           0.90       114
   macro avg       0.91      0.88      0.89       114
weighted avg       0.90      0.90      0.90       114
 



In [ ]:
유방암 분류 문제에서 가장 좋은 성능을 낸 모델 : Random forest 

In [ ]:
우선 성능지표 : 레이블 0에서의 Recall점수

근거
각 모델의 classification report를 보면
악성(malignant) 레이블이 0, 양성(benign)레이블이 1이다. 
실제로 악성인 사람 중에 모델이 악성이라고 분류한 비율인 Recall이
모델이 악성이라고 분류한 사람중에 실제로 악성인 사람의 비율인 Precision보다 높아야 한다.
모델이 양성을 악성으로 잘못 분류(FP)한 것이 악성을 양성으로 잘못 분류(FN)한 것보다 낫기 때문이다.

따라서 레이블 0에서 recall이 가장 높게 나온 모델인 Random forest가 최선의 모델이라 할 수 있다.